<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SamaHesabApiTray</AssemblyName>
    <RootNamespace>SamaHesab.ApiTray</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>tray.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="tray.ico" />
    <Content Include="tray.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
