-- Windows / SQL Express friendly database creation (default data directory)
USE master;
GO
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'SamaHesab')
BEGIN
    ALTER DATABASE SamaHesab SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE SamaHesab;
END
GO
CREATE DATABASE SamaHesab COLLATE Persian_100_CI_AI;
GO
ALTER DATABASE SamaHesab SET RECOVERY SIMPLE;
GO
ALTER DATABASE SamaHesab SET ALLOW_SNAPSHOT_ISOLATION ON;
GO
ALTER DATABASE SamaHesab SET READ_COMMITTED_SNAPSHOT ON;
GO
USE SamaHesab;
GO
CREATE SCHEMA Acc;
GO
CREATE SCHEMA Inv;
GO
CREATE SCHEMA Sal;
GO
CREATE SCHEMA Pur;
GO
CREATE SCHEMA Pos;
GO
CREATE SCHEMA Crm;
GO
CREATE SCHEMA Hrm;
GO
CREATE SCHEMA Cfg;
GO
CREATE SCHEMA Sec;
GO
